#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (runs the installed window manager via Xorg)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/*; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

# Start Pulseaudio
pulseaudio --start

# Set Wallpapers
# feh --randomize --bg-fill ~/Wallpapers/

# Execute Window Manager
xhost + local:
#slstatus &
#exec dbus-launch --sh-syntax --exit-with-session dwm
